language: ruby
rvm:
  - 2.2
deploy:
  provider: heroku
  api_key:
    secure: dYE5eZAYo8q4lsYU85UD+RAfc4gGW05gl6MxotsvAmXeUNj0XwMBN8sDq304l/6WtzEjPWBGp7SpXp6kTOzPXs8u9umF6Ad19zwoyl6p3sWqtP5PDy6xQOnLfu6aLE2iZWtbz3m4NElhz7iU7VktTte06EWQM7v8xuT63EfQfdT3dwIZqcxwvWkOdLfS4UTfCXYDBkafe5uzGiGnJUJSrXOPPAIumisT1mFGsnRSW8JgUvN+u95Z5X0QeiVB2chzSP9uGsR07E/BpFmw2wt9vVOwY7tqyjCR70TxvQYuTPSItJ0UMhDEFDriCYmTKZF9soW5Bday+eXqdFAfWGBCaxHBvA497dTP611EEUOqRGL2+4IkOEjMLaIp/DeYb04X6ed3SW+xslpT7nkEufD/FZY8SMKCzCAGp+++vPWKi0H95fwI5WO7jlsS1g6L32vy+GkzkPQUwUOiLAYGl0LwxuZC2NpwHpeYPRFpswNKkwja5qxFrQiFuKsn7KNbNP0TttZytWY3xnMcDnp5AXkqDAJFIRgbTC8a5hgbQzBVTPThylotGfIUlHp98Sl9LgCnjNTI9heIOYuUdNYoXKg5MBdZZfYyr7aLqV1L+9KnO3lcAlBcAkIxCmaUD88ViN7864EVmnFOW8XRHqwajR6z0ds/PnwNtJ5IbECdsU0n8Ro=
